import type { ChatMessage, FlexPoolTask, Priority } from '@/lib/types';

function toSentence(value: string): string {
  return value
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/[.\s]+$/, '');
}

function splitGoalToActions(goal: string): string[] {
  const cleaned = goal.replace(/[\n;]+/g, ',');
  const chunks = cleaned
    .split(/,| and | then |以及|并且|然后/gi)
    .map((part) => toSentence(part))
    .filter((part) => part.length >= 4);

  const unique = new Set<string>();
  chunks.forEach((chunk) => unique.add(chunk));
  return [...unique].slice(0, 8);
}

function toPriority(index: number): Priority {
  if (index % 3 === 0) return 'P0';
  if (index % 2 === 0) return 'P1';
  return 'P2';
}

// Lightweight deterministic agent: turns user intent into explicit planning instructions.
export function buildAgentPlanningPrompt(goal: string, history: ChatMessage[] = []): string {
  const actions = splitGoalToActions(goal);
  const lastUserMessage = [...history].reverse().find((m) => m.role === 'user')?.content?.trim();

  if (actions.length === 0) {
    return toSentence(goal || lastUserMessage || 'Plan my week with focused deep-work sessions');
  }

  return actions
    .map((action, idx) => `Task ${idx + 1}: ${action}`)
    .join(', ');
}

export function buildHeuristicAgentTasks(goal: string, history: ChatMessage[] = []): FlexPoolTask[] {
  const actions = splitGoalToActions(goal);
  const fallback =
    toSentence(goal || [...history].reverse().find((m) => m.role === 'user')?.content || '') ||
    'Deep work block';

  const base = actions.length > 0 ? actions : [fallback, `${fallback} review`, `${fallback} practice`];

  return base.slice(0, 8).map((title, idx) => ({
    id: `heuristic:${Date.now()}:${idx}`,
    title,
    durationMinutes: idx % 2 === 0 ? 90 : 60,
    priority: toPriority(idx),
    category: 'study',
    notes: 'Generated by local fallback planner.'
  }));
}
